### ISSUE TITLE
Missing "For you" and "Following"

### ISSUE THREAD

**Issue by justlorain** [wangrongding/github-old-feed#3]
I had completed the three steps in Usage and the script is enabled, but my GitHub page did not have the "For you" and "Following" sections. I'm not sure if this is a bug or if I'm doing something wrong.
![image](https://github.com/wangrongding/github-old-feed/assets/87760338/7a606659-7498-4f6d-b1ed-253855fb5c2b)

**Comment by wangrongding** [comment]
Because github removed them, see:https://github.com/dashboard-feed
