### ISSUE TITLE
Please add checks before applying styles

### ISSUE THREAD

**Issue by Tatsh** [wangrongding/github-old-feed#4]
I seem to have a conflicting script or extension. I am probably not the only one.

```javascript
  if (feedContent)
    feedContent.style.maxWidth = "unset"
  if (feedMain)
    feedMain.style.maxWidth = "100%"
  if (sidebar) {
    sidebar.style.maxWidth = "unset"
    sidebar.style.width = "900px"
  }
```

I do not mind the styles applied but others might. Your script is really only expected to restore the feed, not apply styles unless absolutely necessary.

**Comment by Teraskull** [comment]
Ideally, this would be an extension, not a Tampermonkey script, where in the `manifest.json` you can add:

```json
"matches": [
    "*://github.com/",
    "*://github.com/dashboard"
],
```

This will only run the script on these two pages, so it will not raise errors on other pages.

**Comment by wangrongding** [comment]
> Tampermonkey script

@Teraskull  Such a simple script, there is no need to make a extension, and tampermonkey script support only in the matching domain name role.

**Comment by Tatsh** [comment]
Thanks for doing this. Fixed with https://github.com/wangrongding/github-old-feed/commit/7d40b40efbbe19087efbd4053419c189780969e9
